---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
  namespace: workflow
type: Opaque
stringData:
  config.json: |
    {
      "auths": {
        "mysticstorage.local:8443": {
          "auth": "YWRtaW46SGFyYm9yMTIzNDU="
        }
      }
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-ca-secret
  namespace: workflow
type: Opaque
stringData:
  harbor-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFdjCCA16gAwIBAgIUHV9qk0C1Mm2FmedVYwni7uPFYq4wDQYJKoZIhvcNAQEL
    BQAwPDEcMBoGA1UEAwwTbXlzdGljc3RvcmFnZS5sb2NhbDEcMBoGA1UECgwTbXlz
    dGljc3RvcmFnZS5sb2NhbDAeFw0yMzExMDQwOTUzMTRaFw0zMzExMDEwOTUzMTRa
    MDwxHDAaBgNVBAMME215c3RpY3N0b3JhZ2UubG9jYWwxHDAaBgNVBAoME215c3Rp
    Y3N0b3JhZ2UubG9jYWwwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDM
    G10Ay5eY3Y8RQltNaMnDxVMLrfP4lT9IDBZH4OLB+MpRGl4xrd3hnwRPsjag28Gn
    NtVMekoLHm/9wbXEWlGstpW42bQwzbWL77R8XDInByeRRtUQW/LMyJlvux8IEezE
    LUu7eMPYWD5g/bZbDMlHe03i2BvC/7jdYX3Z4P6mkwwQCGZwQvfQZqSD2ooInGJK
    E57cs12LgKCRrXyCX7XfJAP7CCqTbDJXBtPHLaSdsWxhwNq5LDLumYkBtIkIp4qE
    zIo4hr1kVdGkw0tnfKu6QdAcsKfiKWKucpPfMInFH+3i8G7FR8fJCdWvKA0+3Hqv
    VoDTHwqbr/TUkZ0RQypgsV2vVShUwTOZuE/SFAY/dcpoRNtaA+iPg8v3M3WnlcFs
    3erDJ2pSEvlK3c8tg4ja72MkwQv1lozcjMSAQHFF4iLKoBNW9xBLZrsJ1gjz+O1e
    jFi38qHejzJZwXrjedAboeNcM6HQAPJgNvE0gPjZScyoUOBFgA/hwmTCWpuC1W2B
    9hUH5XoVC4ZKEuRZJVywudACZ1xumF8CHDeXse9taH2K9ELCY/0gG/WnM/1ACORK
    Lw1/hJmI6ZlcJmsWDgIyCJ3Q06saAzBI3OR6C+JLyaktbqM1t9T/dG1YSjxYaci1
    J0OOVgG3kZNou9pj9bY4YcfMqu2zmwgpohRKq8MwWwIDAQABo3AwbjAdBgNVHQ4E
    FgQUrj5D0x8iLssHxHlWqMmQu9iiQ70wHwYDVR0jBBgwFoAUrj5D0x8iLssHxHlW
    qMmQu9iiQ70wDAYDVR0TBAUwAwEB/zAeBgNVHREEFzAVghNteXN0aWNzdG9yYWdl
    LmxvY2FsMA0GCSqGSIb3DQEBCwUAA4ICAQB1QkZCxmLNg+P+wgksxHhJacRVNNmg
    N1coZO+KxvMYyJVZO1PT1yqC6SWVixh2sMgGp+7bYhntrZeXAldBGNebNePWh1Yk
    gdjAiNwJtHRwATMVjKFlrBdiH7m1KrvXBsDXjv8h0tHQL0oCG/EaTAzcmTOcciI1
    F559EoGc48/3/KcyAijnPj41/lKOj7+TGf+yuLfjN2TO3vb5G1KtvYrHghDWH+qi
    9Vyt4Qu0FPP9pZwCnf4x5Sg3EFt0hiCg1qck88h06wx12G54Qm1R3luAI9sII0hV
    Ha+7Lbcb8j5hKhKqpEUjxY2whamJdjsbmGKDagLVOfFwHqbMGASKoGlEmTdRaDTw
    fBlYWW3UatvmQEDUvFgUacgPeaYYLcJ/ygAc+lHXQzEAxHAIns/UuNA7hdbjTd40
    /QmNYABBDsKuMer5Bl3u3yri1NBSq1hfVWcAcOSklnbvjGTlzN7Ale1a1Wf3HcIP
    fGJK+hOBh27s7t3hsmGo8bya34Uiz7LFDcX5STDXkC0z/bFJjbzFsB0jqV9RkmaK
    9mRxVRFJEsJHSt43ngy0q5oZsp2jiLWTU85JMaKo9txunV6QbxSanWBWC71d63ht
    yJ37VPUVntVOYcFTRPM2L3SKBUBYeh1ZXvGg94g3wgLnC3ogTpXw5M+Nn10uelCa
    /nBXUL7HnNSNMw==
    -----END CERTIFICATE-----
