---
apiVersion: v1
kind: Secret
metadata:
  name: minio-env-secret
  namespace: workflow
type: Opaque
stringData:
  AWS_ENDPOINT_URL: http://mysticstorage.local:9000
  AWS_ACCESS_KEY_ID: 7FpuwT2IBqdrcng2vHkI
  AWS_SECRET_ACCESS_KEY: HReNjnBWUedy4vCtpHxTI79MKnCdVIqweBKEwNy0
